/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ac1lp;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Visualy-06
 */
public class InterfacePokemon extends javax.swing.JFrame {
    

    /**
     * Creates new form InterfacePokemon
     */
    public InterfacePokemon() {
        initComponents();
        
       
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxPokemon1 = new javax.swing.JComboBox<>();
        lblImagem1 = new javax.swing.JLabel();
        cbxPokemon2 = new javax.swing.JComboBox<>();
        lblImagem2 = new javax.swing.JLabel();
        jButtonBattle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha seu Pokemon:");

        jLabel2.setText("Escolha o Pokemon Adversário:");

        cbxPokemon1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Charmander", "Squirtle", "Bulbasaur", "Graveler" }));
        cbxPokemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemon1ActionPerformed(evt);
            }
        });

        lblImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1lp/Poke Ball.png"))); // NOI18N

        cbxPokemon2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Charmander", "Squirtle", "Bulbasaur", "Graveler" }));
        cbxPokemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPokemon2ActionPerformed(evt);
            }
        });

        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1lp/Poke Ball.png"))); // NOI18N

        jButtonBattle.setText("BATTLE!");
        jButtonBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBattleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblImagem1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(cbxPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblImagem2)
                        .addContainerGap(113, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbxPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(187, 187, 187))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(375, 375, 375)
                .addComponent(jButtonBattle, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImagem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jButtonBattle))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPokemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemon1ActionPerformed
       
        if (cbxPokemon1.getSelectedIndex()== 0){
            ImageIcon image1 = new ImageIcon(getClass().getResource("Poke Ball.png"));
            lblImagem1.setIcon(new ImageIcon(image1.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));
            
        }   else if(cbxPokemon1.getSelectedIndex()== 1){
       
            ImageIcon image2 = new ImageIcon(getClass().getResource("Charmander.png"));
            lblImagem1.setIcon(new ImageIcon(image2.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
            
           
            
            
        }   else if(cbxPokemon1.getSelectedIndex()== 2){
                                  
            ImageIcon image3 = new ImageIcon(getClass().getResource("Squirtle.png"));
            lblImagem1.setIcon(new ImageIcon(image3.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
                             
        }   else if(cbxPokemon1.getSelectedIndex()== 3){
            ImageIcon image4 = new ImageIcon(getClass().getResource("Bulbasaur.png"));
            lblImagem1.setIcon(new ImageIcon(image4.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
        
        }   else{
            ImageIcon image5 = new ImageIcon(getClass().getResource("Golem.png"));
            lblImagem1.setIcon(new ImageIcon(image5.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));} 
    }//GEN-LAST:event_cbxPokemon1ActionPerformed

    private void cbxPokemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPokemon2ActionPerformed
        if (cbxPokemon2.getSelectedIndex()== 0){
            ImageIcon image1 = new ImageIcon(getClass().getResource("Poke Ball.png"));
            lblImagem2.setIcon(new ImageIcon(image1.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));
        }
            
        else if(cbxPokemon2.getSelectedIndex()== 1){
            
            ImageIcon image2 = new ImageIcon(getClass().getResource("Charmander.png"));
            lblImagem2.setIcon(new ImageIcon(image2.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
                 
        }    
            else if(cbxPokemon2.getSelectedIndex()== 2){
           
           
            ImageIcon image3 = new ImageIcon(getClass().getResource("Squirtle.png"));
            lblImagem2.setIcon(new ImageIcon(image3.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
          
      
            }else if(cbxPokemon2.getSelectedIndex()== 3){
            ImageIcon image4 = new ImageIcon(getClass().getResource("Bulbasaur.png"));
            lblImagem2.setIcon(new ImageIcon(image4.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));  
        }   
            else{
                ImageIcon image5 = new ImageIcon(getClass().getResource("Golem.png"));
                lblImagem2.setIcon(new ImageIcon(image5.getImage().getScaledInstance(lblImagem1.getWidth(),lblImagem1.getHeight(), Image.SCALE_DEFAULT)));} 
                                                  
    }//GEN-LAST:event_cbxPokemon2ActionPerformed

    private void jButtonBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBattleActionPerformed
    
        
    if (cbxPokemon1.getSelectedIndex()== 1 && cbxPokemon2.getSelectedIndex()== 2){
               
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);
    

    
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(charmander.getNome(), charmander.getVida());
    batalha.outroPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.startBattle();
    
    } else if (cbxPokemon1.getSelectedIndex()== 1 && cbxPokemon2.getSelectedIndex()== 3){
               
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);

    
    
    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);

    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(charmander.getNome(), charmander.getVida());
    batalha.outroPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.startBattle();
    
    }else if(cbxPokemon1.getSelectedIndex()== 1 && cbxPokemon2.getSelectedIndex()== 4){
               
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);

    
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);

    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(charmander.getNome(), charmander.getVida());
    batalha.outroPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.startBattle();                   
    }
    
     if (cbxPokemon1.getSelectedIndex()== 2 && cbxPokemon2.getSelectedIndex()== 1){
    
    
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

               
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);

    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.outroPokemon(charmander.getNome(), charmander.getVida());
    batalha.startBattle();
    
    }else if(cbxPokemon1.getSelectedIndex()== 2 && cbxPokemon2.getSelectedIndex()== 3){
    
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

    
    
    
    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);

    
    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.outroPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.startBattle();                   
    
    }else if(cbxPokemon1.getSelectedIndex()== 2 && cbxPokemon2.getSelectedIndex()== 4){
    
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

    
    
    
    
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);

    
    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.outroPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.startBattle();                   
    
    }
     
     if (cbxPokemon1.getSelectedIndex()== 3 && cbxPokemon2.getSelectedIndex()== 1){
      
    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);
      
    
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);

    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.outroPokemon(charmander.getNome(), charmander.getVida());
    batalha.startBattle();
    }
     else if(cbxPokemon1.getSelectedIndex()== 3 && cbxPokemon2.getSelectedIndex()== 2){
    
    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);

   
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.outroPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.startBattle();                   
    }
     
     else if(cbxPokemon1.getSelectedIndex()== 3 && cbxPokemon2.getSelectedIndex()== 4){
    
    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);

   
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);

    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.outroPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.startBattle();                   
    }
     
    if (cbxPokemon1.getSelectedIndex()== 4 && cbxPokemon2.getSelectedIndex()== 1){
      
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);

    
    Pokemon charmander = new Pokemon("Charmander", "Fogo", 10);

    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.outroPokemon(charmander.getNome(), charmander.getVida());
    batalha.startBattle();
    
    }
    else if(cbxPokemon1.getSelectedIndex()== 4 && cbxPokemon2.getSelectedIndex()== 2){
    
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);
    
    
    Pokemon squirtle = new Pokemon("Squirtle", "Água", 10);

    
    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.outroPokemon(squirtle.getNome(), squirtle.getVida());
    batalha.startBattle();                   
    } 
    
    else if(cbxPokemon1.getSelectedIndex()== 4 && cbxPokemon2.getSelectedIndex()== 3){
    
    Pokemon Graveler = new Pokemon("Graveler", "Pedra", 10);

    Pokemon Bulbasaur = new Pokemon("Bulbasaur", "Planta", 10);

   
    
    
    Batalhas batalha = new Batalhas();
    batalha.meuPokemon(Graveler.getNome(), Graveler.getVida());
    batalha.outroPokemon(Bulbasaur.getNome(), Bulbasaur.getVida());
    batalha.startBattle();
    
    }
    
    // empates
    
    if(cbxPokemon1.getSelectedIndex() == 1 && cbxPokemon2.getSelectedIndex()== 1){
        
        JOptionPane.showMessageDialog(null, "A batalha vai começar!",        
        "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
        String mensagem = "A batalha começará em: ";
          
        for (int i = 3; i > 0; i--) {
            mensagem += i + "... ";
        
            JOptionPane.showMessageDialog(null, mensagem,
                "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
        }
        
        JOptionPane.showMessageDialog(null, " Empate! ",
        "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
       
        }else if(cbxPokemon1.getSelectedIndex() == 2 && cbxPokemon2.getSelectedIndex()== 2){
        
            JOptionPane.showMessageDialog(null, "A batalha vai começar!",        
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            String mensagem = "A batalha começará em: ";
          
            for (int i = 3; i > 0; i--) {
            mensagem += i + "... ";
        
            JOptionPane.showMessageDialog(null, mensagem,
                "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            }
        
            JOptionPane.showMessageDialog(null, " Empate! ",
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
        
        }else if(cbxPokemon1.getSelectedIndex() == 3 && cbxPokemon2.getSelectedIndex()== 3){
        
            JOptionPane.showMessageDialog(null, "A batalha vai começar!",        
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            String mensagem = "A batalha começará em: ";
          
            for (int i = 3; i > 0; i--) {
            mensagem += i + "... ";
        
            JOptionPane.showMessageDialog(null, mensagem,
                "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            }
        
            JOptionPane.showMessageDialog(null, " Empate! ",
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
        
        }else if(cbxPokemon1.getSelectedIndex() == 4 && cbxPokemon2.getSelectedIndex()== 4){
        
            JOptionPane.showMessageDialog(null, "A batalha vai começar!",        
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            String mensagem = "A batalha começará em: ";
          
            for (int i = 3; i > 0; i--) {
            mensagem += i + "... ";
        
            JOptionPane.showMessageDialog(null, mensagem,
                "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            }
        
            JOptionPane.showMessageDialog(null, " Empate! ",
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
        }else if(cbxPokemon1.getSelectedIndex() == 0 && cbxPokemon2.getSelectedIndex()== 0){
            
            
    JOptionPane.showMessageDialog(null, "Treinadores selecionem seus Pokemons, Pokebolas não batalham sozinhas!! ",
            "Batalha de Pokemons", JOptionPane.INFORMATION_MESSAGE);
            
        }
    

    
    
   
    }//GEN-LAST:event_jButtonBattleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxPokemon1;
    private javax.swing.JComboBox<String> cbxPokemon2;
    private javax.swing.JButton jButtonBattle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem1;
    private javax.swing.JLabel lblImagem2;
    // End of variables declaration//GEN-END:variables
}
